// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAppVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function MssqlQuery(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.QueryResult>;
